version: '3.8'

services:
  # Data base
  db:
    image: ankane/pgvector:latest
    container_name: ragdm_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ragdm_backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GIN_MODE=${GIN_MODE}
    restart: unless-stopped

volumes:
  pgdata: