name: CI Check

on:
  push:
    branches: [ "main", "feature/spaced-rep-algorithm" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: sudo apt-get update && sudo apt-get install -y cmake clang clang-tidy ninja-build

    - name: Run Clang-Tidy
      working-directory: ./algorithm
      run: |
        clang-tidy src/algorithm.c -- -I./include
        clang-tidy tests/test_algorithm.c -- -I./include

    - name: Build and Run
      working-directory: ./algorithm
      run: |
        mkdir build && cd build
        cmake -G Ninja ..
        ninja
        ./test_algorithm